global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ranx-proxy'
    static_configs:
      - targets: ['proxy:8080']
    metrics_path: '/metrics'
    scheme: 'http' 
